# pubspec.yaml

name: cool_package # use separate package names with underscores
version: 1.2.3 # use semver
description: >
  A really cool package that allows you to
  reticulate your splines and transmogrify
  your unidirectional dataflow.
author: John Ryan
homepage: johnpryan.github.io
environment:
  sdk: ">=0.12.0"
documentation: http://docs.coolpackagedartlang.com
dependencies:
  yaml: ^2.1.0
  frappe: ^0.4.0
dev_dependencies:
  test: ^0.12.0

# Overridden dependencies force all packages
# in the dependency graph to use a specific version
# (since only one version of a package is allowed)
dependency_overrides:
  stream_transformers: 0.2.0

  # If you are developing a package (yaml) locally,
  # it's convenient to override using a path depencency
  yaml:
    path: ../yaml

