name: dartbyexample
publish_to: none
environment:
  sdk: '>=2.10.0 <3.0.0'
dependencies:
  tavern: ^3.2.1
  http: ^0.12.0
  mustache: ^1.0.0
  markdown: ^2.0.0
dev_dependencies:
  build_runner: any
  sass_builder: any
